<div class="form_proposal_container">
	<form action="/index/sendProposal/" accept-charset="utf-8" method="post" enctype="multipart/form-data">
	
		<div class="form_row">
			<label class="item_title">Proposed budget</label>
			<input type="text" name="budget">
		</div>
				
		<div class="form_row">
			<label class="item_title">Proposal</label>
			<textarea type="text" name="proposal"></textarea>
		</div>	
	
		<div class="form_row">
			<label class="item_title">Add atachment</label>
			<input type="text" name="file">
		</div>
		
		<input type="submit">
		
	</form>
</div>