<?php
if(isset($this->message))
{
	print $this->message;
}
print $this->form;

?>
<!--<div class="form_proposal_container">
	<form action="/index/sendProposal/" accept-charset="utf-8" method="post" enctype="multipart/form-data">
	
		<div class="form_row">
			<label class="item_title">First Name</label>
			<input type="text" name="first_name">
		</div>
		
		<div class="form_row">
			<label class="item_title">Last Name</label>
			<input type="text" name="last_name">
		</div>
		
		<div class="form_row">
			<label class="item_title">Company Name</label>
			<input type="text" name="company_name">
		</div>
		
		<div class="form_row">
			<label class="item_title">Street</label>
			<input type="text" name="street">
		</div>
		
		<div class="form_row">
			<label class="item_title">State/Province</label>
			<input type="text" name="state_province">
		</div>
		
		<div class="form_row">
			<label class="item_title">Post Code</label>
			<input type="text" name="post_code">
		</div>
		
		<div class="form_row">
			<label class="item_title">Email</label>
			<input type="text" name="email">
		</div>
		
		<div class="form_row">
			<label class="item_title">UserName</label>
			<input type="text" name="username">
		</div>
		
		<div class="form_row">
			<label class="item_title">Password</label>
			<input type="text" name="password">
		</div>
		
		<div class="form_row">
			<label class="item_title">Confrm Password</label>
			<input type="text" name="password_again">
		</div>
		
		<input type="submit">
		
	</form>
</div>
-->