<div id="content_bottom">
	<div id="content_bottom_inner">
	<?php
	if(isset($this->message_not_logged)) {
		print $this->message_not_logged;
	} else 
	{
?>
	<div id="step3_3">
        <script type="text/javascript">
            document.write(unescape("%3Cscript id=%27pap_x2s6df8d%27 src=%27" + (("https:" == document.location.protocol) ? "https://" : "http://") + "searchfreelancejobs.postaffiliatepro.com/scripts/trackjs.js%27 type=%27text/javascript%27%3E%3C/script%3E"));
        </script> <script type="text/javascript">
            PostAffTracker.setAccountId('default1');
            var sale = PostAffTracker.createSale();
            sale.setTotalCost('120.50');
            sale.setOrderID('ORD_12345XYZ');
            sale.setProductID('test product');
            PostAffTracker.register();
        </script>
		<span class="step3_congrate">
			Congratulations! Start bidding on jobs below. You can also filter your results on the right hand side.
		</span>
		<div class="align_center">
			<a class="blue_submit a_std_btn" href="/index/index/">Continue</a>
		</div> 
		
	</div>
<?php
	}
?>
	</div>
</div>