    <div id="content_bottom">
        
       	<div id="content_bottom_inner">
        
        	<div id="profile_menu" class="outer_block">
            
            	<div id="profile_menu_inner" class="inner_block">
                	
                    <ul>
                    	<li><a href="#">Dashboard</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Payment</a></li>
                        <li><a href="#">Setting</a></li>
                        <li><a href="#">My Jobs</a></li>
                        <li><a href="#">My Messages&nbsp;<span>5</span></a></li>
                    </ul>
                
                </div><!--profile_menu_inner-->
            
            </div><!--profile_menu-->
        
        	<div id="profile_block" class="outer_block">
            
            	<div id="profile_block_inner" class="inner_block">
                
                	<img src="/media/public/users_portrait.jpg" alt="" title="" id="users_portrait" />
                    
                    <ul id="users_info">
                    	<li id="ui_title"><span class="span_1">Welcome,</span>&nbsp;<span class="span_2">Eric Anonimous</span></li>
                        <li id="ui_email"><span class="span_1">Personal Email:</span>&nbsp;<span class="span_2">eric@piekinc.com</span>&nbsp;<span id="change_email" class="span_3">(&nbsp;change&nbsp;)</span></li>
                        <li id="ui_bids"><span class="span_1">Bid On Project</span>&nbsp;<span class="span_2">You have bid 47 bids</span></li>
                    </ul>
                    
                    <div id="login_time_box">
                    	Your last login was on&nbsp;<span id="lt_date">Feb 14, 2012</span>&nbsp;at&nbsp;<span id="lt_time">19:02 WET</span>
                    </div>
                    
                    <div class="clear"></div>
                    
                   	<span id="portrait_title">Portrait</span>

                    <a id="profile_edit" href="#" onclick="return false;"><img src="/media/image/buttons/btn_edit.png" alt="" title="" /></a>
                
                </div><!--profile_block_inner-->
            
            </div><!--profile_block-->
            
            <div id="recommended_projects_outer" class="outer_block">
            
            	<div id="recommended_projects_inner" class="inner_block">
                	
                    <div class="title">
                    	<div class="subtitle">
                        	<img src="/media/image/elements/suitcase.png" alt="" title="" /><span>Recommended projects</span>
                        </div>
                    </div>
                
                	<div class="row">
                    	<p>Need 1000 Facebook Fans</p>
                    	<span>Our company will be placing an advertisement in a major architectural magazine in the The goal of 
this project is to develop that ad. The advertisement will be a 1/6th page ad.</span>
	                    <a href="#" class="more">more ...</a>
                    </div><!--row-->
                    
                    <div class="row">
                    	<p>Need 1000 Facebook Fans</p>
                    	<span>Our company will be placing an advertisement in a major architectural magazine in the The goal of 
this project is to develop that ad. The advertisement will be a 1/6th page ad.</span>
	                    <a href="#" class="more">more ...</a>
                    </div><!--row-->
                    
                    <div class="row">
                    	<p>Need 1000 Facebook Fans</p>
                    	<span>Our company will be placing an advertisement in a major architectural magazine in the The goal of 
this project is to develop that ad. The advertisement will be a 1/6th page ad.</span>
	                    <a href="#" class="more">more ...</a>
                    </div><!--row-->
                    
                    <div class="row">
                    	<p>Need 1000 Facebook Fans</p>
                    	<span>Our company will be placing an advertisement in a major architectural magazine in the The goal of 
this project is to develop that ad. The advertisement will be a 1/6th page ad.</span>
	                    <a href="#" class="more">more ...</a>
                    </div><!--row-->
                    
                    <div class="row">
                    	<p>Need 1000 Facebook Fans</p>
                    	<span>Our company will be placing an advertisement in a major architectural magazine in the The goal of 
this project is to develop that ad. The advertisement will be a 1/6th page ad.</span>
	                    <a href="#" class="more">more ...</a>
                    </div><!--row-->
                    
                </div><!--recommended_projects_inner-->
                
            </div><!--recommended_projects-->
            
            <div id="recent_job_outer" class="outer_block">
            
            	<div id="recent_job_inner" class="inner_block">
                
                	<div class="title">
                    	<div class="subtitle">
                        	<img src="/media/image/elements/arrow_down_2.png" alt="" title="" /><span>Recent Job Application</span>
                        </div>
                    </div>
                    
                    <div class="row">
                    	<span class="text">Your Job application has been Succesfull submited for</span>
                    	<span class="job_title">Need 1000 Facebook Fans</span>
	                    <span class="time_ago">at 20 Hours Ago</span>
                    </div><!--row-->
                    
                    <div class="row">
                    	<span class="text">Your Job application has been Succesfull submited for</span>
                    	<span class="job_title">Need 1000 Facebook Fans</span>
	                    <span class="time_ago">at 20 Hours Ago</span>
                    </div><!--row-->
                    
                    <div class="row">
                    	<span class="text">Your Job application has been Succesfull submited for</span>
                    	<span class="job_title">Need 1000 Facebook Fans</span>
	                    <span class="time_ago">at 20 Hours Ago</span>
                    </div><!--row-->
                    
                    <div class="row">
                    	<span class="text">Your Job application has been Succesfull submited for</span>
                    	<span class="job_title">Need 1000 Facebook Fans</span>
	                    <span class="time_ago">at 20 Hours Ago</span>
                    </div><!--row-->
                    
                    <div class="row">
                    	<span class="text">Your Job application has been Succesfull submited for</span>
                    	<span class="job_title">Need 1000 Facebook Fans</span>
	                    <span class="time_ago">at 20 Hours Ago</span>
                    </div><!--row-->
                    
                    <div class="row">
                    	<span class="text">Your Job application has been Succesfull submited for</span>
                    	<span class="job_title">Need 1000 Facebook Fans</span>
	                    <span class="time_ago">at 20 Hours Ago</span>
                    </div><!--row-->
                    
                </div><!--recent_job_inner-->
            </div><!--recent_job_outer-->
        
        	
        
        </div><!--content_bottom_inner-->
        
    </div><!--content_bottom-->
    
    <div class="clear"></div>
