<?php $this->headTitle('Platforms') ?>
<script>
function status_update(id,status){
  alert(id+'*******'+status);	
}
</script>
<ul class="breadcrumb">
  <li><a href="/adminpanel/">Adminpanel</a> <span class="divider">/</span></li>
  <li>Platforms</li>
</ul>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> # </th>
            <th> Logo </th>
            <th> Name </th>
            <th> url </th>
            <th style="width: 100px;"> Status </th>
            <th style="width: 160px;"> </th>
        </tr>
    </thead>
    <tbody>
        <?php   //echo "<pre>"; print_r($this->paginator);
	  //die;  
	  
	  
	  foreach ($this->paginator as $platform): ?>
        <tr>
            <td> <?= (int)$platform->id ?> </td>
            <td> <img title="<?= $this->escape($platform->name) ?>" alt="" src="/media/image/logos/<?= $platform->logo ?>"> </td>
            <td> <?= $this->escape($platform->name) ?> </td>
            <td> <?= $this->escape($platform->url) ?> </td>
            <td><?php if($platform->active==1){ echo '<img title="Active" src="/media/image/active_icon.png" onclick="status_update('.(int)$platform->id.','.$platform->active.')" style="cursor:pointer;">';}else{ echo '<img title="Inactive" src="/media/image/inactive_icon.png" onclick="status_update('.(int)$platform->id.','.$platform->active.')" style="cursor:pointer;">';}?></td>
            <td>
                <a href="/adminpanel/platform-edit/id/<?= (int)$platform->id ?>" class="btn btn-primary">
                    <i class="icon-pencil icon-white"></i>
                    Edit
                </a>
                <a href="/adminpanel/platform-delete/id/<?= (int)$platform->id ?>" onclick="return confirm('Are you sure you want to delete the Platform?');" class="btn btn-danger" style="cursor:pointer;">
                    <i class="icon-trash icon-white"></i>
                    Delete
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?= $this->paginator ?>