<div id="header_center">
    <div id="header_center_inner">
        <img src="/media/image/new-logo.png" class="free_fm_header">
        <div class="ptc_registered">
        <?php /*
        <span class="ptc_registered2">Registered for <b><?php echo $this->platform['name'] ?></b>?</span>
        */ ?>
        <a href="<?= isset($_GET['back']) ? $_GET['back'] : '/' ?>" target="_parent">Click here to continue bidding on SearchFreelanceJobs.com</a>
        </div>
    </div>
</div>