CREATE TABLE `bids` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INTEGER UNSIGNED NOT NULL,
  `project_id` INTEGER UNSIGNED NOT NULL,
  `added` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;